### ISSUE TITLE
can not conver the bvlc_googlenet.caffemodel

### ISSUE THREAD

**Issue by sxsxsx** [Tencent/FeatherCNN#13]
Hello，thank you for your contributions for the FeatherCNN，I have a question that when I use ./feather_convert_caffe bvlc_googlenet.prototxt bvlc_googlenet.caffemodel to conver bvlc_googlenet.caffemodel, it gets something wrong:

Input Num 0
Input Layer
Input dim 10
Input dim 3
Input dim 224
Input dim 224
Layer num 0
Legacy layer num 169
[libprotobuf FATAL /usr/local/include/google/protobuf/repeated_field.h:1522] CHECK failed: (index) < (current_size_): 
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: (index) < (current_size_): 
Aborted (core dumped)
 
 Is it wrong with my bvlc_googlenet.prototxt? I download the prototxt from https://github.com/BVLC/caffe/blob/master/models/bvlc_googlenet/deploy.prototxt and the caffmodel was downloaded from 
 http://dl.caffe.berkeleyvision.org/bvlc_googlenet.caffemodel

ubantu16.04 64Bit Host
 Looking forward to your reply!
 Thanks in advance!

**Comment by turbo0628** [comment]
Thanks for reporting. Seems that caffe cannot load its own protobuf, I'll check the problem in a few days.

**Comment by sxsxsx** [comment]
I'm glad to receive your reply，I solved this problem by using upgrade_net_proto_binary.exe to upgrade the bvlc_googlenet.caffemodel ，and it is  successful to conver the caffemodel to the feathermodel，but I have new questions while running on the rk3288(armeabi-v7a)
host:ubantu16.04 NDK r17

1、bvlc_googlenet.feathermodel   
++++++Start Loader++++++
Finished loading from file
-- Loading 143 layers
input num 1 input dim num 4
input_name data (n c h w) (1 3 224 224)
stride 2, 2
_bottom data
setup layer conv1/7x7_s2
_bottom conv1/7x7_s2
setup layer conv1/relu_7x7
_bottom conv1/relu_7x7
kernel (3 3) pad (0 0) stride (2 2) global_pooling 0
setup layer pool1/3x3_s2
_bottom pool1/3x3_s2
localsize 5 alpha 0.000100 beta 0.750000 k 1.000000
setup layer pool1/norm1
stride 1, 1
_bottom pool1/norm1
setup layer conv2/3x3_reduce
_bottom conv2/3x3_reduce
setup layer conv2/relu_3x3_reduce
stride 1, 1
_bottom conv2/relu_3x3_reduce
setup layer conv2/3x3
_bottom conv2/3x3
setup layer conv2/relu_3x3
_bottom conv2/relu_3x3
localsize 5 alpha 0.000100 beta 0.750000 k 1.000000
setup layer conv2/norm2
_bottom conv2/norm2
kernel (3 3) pad (0 0) stride (2 2) global_pooling 0
setup layer pool2/3x3_s2
stride 1, 1
_bottom pool2/3x3_s2
setup layer inception_3a/1x1
_bottom inception_3a/1x1
setup layer inception_3a/relu_1x1
stride 1, 1
_bottom pool2/3x3_s2
setup layer inception_3a/3x3_reduce
_bottom inception_3a/3x3_reduce
setup layer inception_3a/relu_3x3_reduce
stride 1, 1
_bottom inception_3a/relu_3x3_reduce
setup layer inception_3a/3x3
_bottom inception_3a/3x3
setup layer inception_3a/relu_3x3
stride 1, 1
_bottom pool2/3x3_s2
setup layer inception_3a/5x5_reduce
_bottom inception_3a/5x5_reduce
setup layer inception_3a/relu_5x5_reduce
stride 1, 1
_bottom inception_3a/relu_5x5_reduce
setup layer inception_3a/5x5
_bottom inception_3a/5x5
setup layer inception_3a/relu_5x5
_bottom pool2/3x3_s2
kernel (3 3) pad (1 1) stride (1 1) global_pooling 0
setup layer inception_3a/pool
stride 1, 1
_bottom inception_3a/pool
setup layer inception_3a/pool_proj
_bottom inception_3a/pool_proj
setup layer inception_3a/relu_pool_proj
_bottom inception_3a/relu_1x1
_bottom inception_3a/relu_3x3
_bottom inception_3a/relu_5x5
_bottom inception_3a/relu_pool_proj
setup layer inception_3a/output
stride 1, 1
_bottom inception_3a/output
setup layer inception_3b/1x1
_bottom inception_3b/1x1
setup layer inception_3b/relu_1x1
stride 1, 1
_bottom inception_3a/output
setup layer inception_3b/3x3_reduce
_bottom inception_3b/3x3_reduce
setup layer inception_3b/relu_3x3_reduce
stride 1, 1
_bottom inception_3b/relu_3x3_reduce
setup layer inception_3b/3x3
_bottom inception_3b/3x3
setup layer inception_3b/relu_3x3
stride 1, 1
_bottom inception_3a/output
setup layer inception_3b/5x5_reduce
_bottom inception_3b/5x5_reduce
setup layer inception_3b/relu_5x5_reduce
stride 1, 1
_bottom inception_3b/relu_5x5_reduce
setup layer inception_3b/5x5
_bottom inception_3b/5x5
setup layer inception_3b/relu_5x5
_bottom inception_3a/output
kernel (3 3) pad (1 1) stride (1 1) global_pooling 0
setup layer inception_3b/pool
stride 1, 1
_bottom inception_3b/pool
setup layer inception_3b/pool_proj
_bottom inception_3b/pool_proj
setup layer inception_3b/relu_pool_proj
_bottom inception_3b/relu_1x1
_bottom inception_3b/relu_3x3
_bottom inception_3b/relu_5x5
_bottom inception_3b/relu_pool_proj
setup layer inception_3b/output
_bottom inception_3b/output
kernel (3 3) pad (0 0) stride (2 2) global_pooling 0
setup layer pool3/3x3_s2
stride 1, 1
_bottom pool3/3x3_s2
setup layer inception_4a/1x1
_bottom inception_4a/1x1
setup layer inception_4a/relu_1x1
stride 1, 1
_bottom pool3/3x3_s2
setup layer inception_4a/3x3_reduce
_bottom inception_4a/3x3_reduce
setup layer inception_4a/relu_3x3_reduce
stride 1, 1
_bottom inception_4a/relu_3x3_reduce
setup layer inception_4a/3x3
_bottom inception_4a/3x3
setup layer inception_4a/relu_3x3
stride 1, 1
_bottom pool3/3x3_s2
setup layer inception_4a/5x5_reduce
_bottom inception_4a/5x5_reduce
setup layer inception_4a/relu_5x5_reduce
stride 1, 1
_bottom inception_4a/relu_5x5_reduce
setup layer inception_4a/5x5
_bottom inception_4a/5x5
setup layer inception_4a/relu_5x5
_bottom pool3/3x3_s2
kernel (3 3) pad (1 1) stride (1 1) global_pooling 0
setup layer inception_4a/pool
stride 1, 1
_bottom inception_4a/pool
setup layer inception_4a/pool_proj
_bottom inception_4a/pool_proj
setup layer inception_4a/relu_pool_proj
_bottom inception_4a/relu_1x1
_bottom inception_4a/relu_3x3
_bottom inception_4a/relu_5x5
_bottom inception_4a/relu_pool_proj
setup layer inception_4a/output
stride 1, 1
_bottom inception_4a/output
setup layer inception_4b/1x1
_bottom inception_4b/1x1
setup layer inception_4b/relu_1x1
stride 1, 1
_bottom inception_4a/output
setup layer inception_4b/3x3_reduce
_bottom inception_4b/3x3_reduce
setup layer inception_4b/relu_3x3_reduce
stride 1, 1
_bottom inception_4b/relu_3x3_reduce
setup layer inception_4b/3x3
_bottom inception_4b/3x3
setup layer inception_4b/relu_3x3
stride 1, 1
_bottom inception_4a/output
setup layer inception_4b/5x5_reduce
_bottom inception_4b/5x5_reduce
setup layer inception_4b/relu_5x5_reduce
stride 1, 1
_bottom inception_4b/relu_5x5_reduce
setup layer inception_4b/5x5
_bottom inception_4b/5x5
setup layer inception_4b/relu_5x5
_bottom inception_4a/output
kernel (3 3) pad (1 1) stride (1 1) global_pooling 0
setup layer inception_4b/pool
stride 1, 1
_bottom inception_4b/pool
setup layer inception_4b/pool_proj
_bottom inception_4b/pool_proj
setup layer inception_4b/relu_pool_proj
_bottom inception_4b/relu_1x1
_bottom inception_4b/relu_3x3
_bottom inception_4b/relu_5x5
_bottom inception_4b/relu_pool_proj
setup layer inception_4b/output
stride 1, 1
_bottom inception_4b/output
setup layer inception_4c/1x1
_bottom inception_4c/1x1
setup layer inception_4c/relu_1x1
stride 1, 1
_bottom inception_4b/output
setup layer inception_4c/3x3_reduce
_bottom inception_4c/3x3_reduce
setup layer inception_4c/relu_3x3_reduce
stride 1, 1
_bottom inception_4c/relu_3x3_reduce
setup layer inception_4c/3x3
_bottom inception_4c/3x3
setup layer inception_4c/relu_3x3
stride 1, 1
_bottom inception_4b/output
setup layer inception_4c/5x5_reduce
_bottom inception_4c/5x5_reduce
setup layer inception_4c/relu_5x5_reduce
stride 1, 1
_bottom inception_4c/relu_5x5_reduce
setup layer inception_4c/5x5
_bottom inception_4c/5x5
setup layer inception_4c/relu_5x5
_bottom inception_4b/output
kernel (3 3) pad (1 1) stride (1 1) global_pooling 0
setup layer inception_4c/pool
stride 1, 1
_bottom inception_4c/pool
setup layer inception_4c/pool_proj
_bottom inception_4c/pool_proj
setup layer inception_4c/relu_pool_proj
_bottom inception_4c/relu_1x1
_bottom inception_4c/relu_3x3
_bottom inception_4c/relu_5x5
_bottom inception_4c/relu_pool_proj
setup layer inception_4c/output
stride 1, 1
_bottom inception_4c/output
setup layer inception_4d/1x1
_bottom inception_4d/1x1
setup layer inception_4d/relu_1x1
stride 1, 1
_bottom inception_4c/output
setup layer inception_4d/3x3_reduce
_bottom inception_4d/3x3_reduce
setup layer inception_4d/relu_3x3_reduce
stride 1, 1
_bottom inception_4d/relu_3x3_reduce
setup layer inception_4d/3x3
_bottom inception_4d/3x3
setup layer inception_4d/relu_3x3
stride 1, 1
_bottom inception_4c/output
setup layer inception_4d/5x5_reduce
_bottom inception_4d/5x5_reduce
setup layer inception_4d/relu_5x5_reduce
stride 1, 1
_bottom inception_4d/relu_5x5_reduce
setup layer inception_4d/5x5
_bottom inception_4d/5x5
setup layer inception_4d/relu_5x5
_bottom inception_4c/output
kernel (3 3) pad (1 1) stride (1 1) global_pooling 0
setup layer inception_4d/pool
stride 1, 1
_bottom inception_4d/pool
setup layer inception_4d/pool_proj
_bottom inception_4d/pool_proj
setup layer inception_4d/relu_pool_proj
_bottom inception_4d/relu_1x1
_bottom inception_4d/relu_3x3
_bottom inception_4d/relu_5x5
_bottom inception_4d/relu_pool_proj
setup layer inception_4d/output
stride 1, 1
_bottom inception_4d/output
setup layer inception_4e/1x1
_bottom inception_4e/1x1
setup layer inception_4e/relu_1x1
stride 1, 1
_bottom inception_4d/output
setup layer inception_4e/3x3_reduce
_bottom inception_4e/3x3_reduce
setup layer inception_4e/relu_3x3_reduce
stride 1, 1
_bottom inception_4e/relu_3x3_reduce
setup layer inception_4e/3x3
_bottom inception_4e/3x3
setup layer inception_4e/relu_3x3
stride 1, 1
_bottom inception_4d/output
setup layer inception_4e/5x5_reduce
_bottom inception_4e/5x5_reduce
setup layer inception_4e/relu_5x5_reduce
stride 1, 1
_bottom inception_4e/relu_5x5_reduce
setup layer inception_4e/5x5
_bottom inception_4e/5x5
setup layer inception_4e/relu_5x5
_bottom inception_4d/output
kernel (3 3) pad (1 1) stride (1 1) global_pooling 0
setup layer inception_4e/pool
stride 1, 1
_bottom inception_4e/pool
setup layer inception_4e/pool_proj
_bottom inception_4e/pool_proj
setup layer inception_4e/relu_pool_proj
_bottom inception_4e/relu_1x1
_bottom inception_4e/relu_3x3
_bottom inception_4e/relu_5x5
_bottom inception_4e/relu_pool_proj
setup layer inception_4e/output
_bottom inception_4e/output
kernel (3 3) pad (0 0) stride (2 2) global_pooling 0
setup layer pool4/3x3_s2
stride 1, 1
_bottom pool4/3x3_s2
setup layer inception_5a/1x1
_bottom inception_5a/1x1
setup layer inception_5a/relu_1x1
stride 1, 1
_bottom pool4/3x3_s2
setup layer inception_5a/3x3_reduce
_bottom inception_5a/3x3_reduce
setup layer inception_5a/relu_3x3_reduce
stride 1, 1
_bottom inception_5a/relu_3x3_reduce
setup layer inception_5a/3x3
_bottom inception_5a/3x3
setup layer inception_5a/relu_3x3
stride 1, 1
_bottom pool4/3x3_s2
setup layer inception_5a/5x5_reduce
_bottom inception_5a/5x5_reduce
setup layer inception_5a/relu_5x5_reduce
stride 1, 1
_bottom inception_5a/relu_5x5_reduce
setup layer inception_5a/5x5
_bottom inception_5a/5x5
setup layer inception_5a/relu_5x5
_bottom pool4/3x3_s2
kernel (3 3) pad (1 1) stride (1 1) global_pooling 0
setup layer inception_5a/pool
stride 1, 1
_bottom inception_5a/pool
setup layer inception_5a/pool_proj
_bottom inception_5a/pool_proj
setup layer inception_5a/relu_pool_proj
_bottom inception_5a/relu_1x1
_bottom inception_5a/relu_3x3
_bottom inception_5a/relu_5x5
_bottom inception_5a/relu_pool_proj
setup layer inception_5a/output
stride 1, 1
_bottom inception_5a/output
setup layer inception_5b/1x1
_bottom inception_5b/1x1
setup layer inception_5b/relu_1x1
stride 1, 1
_bottom inception_5a/output
setup layer inception_5b/3x3_reduce
_bottom inception_5b/3x3_reduce
setup layer inception_5b/relu_3x3_reduce
stride 1, 1
_bottom inception_5b/relu_3x3_reduce
setup layer inception_5b/3x3
_bottom inception_5b/3x3
setup layer inception_5b/relu_3x3
stride 1, 1
_bottom inception_5a/output
setup layer inception_5b/5x5_reduce
_bottom inception_5b/5x5_reduce
setup layer inception_5b/relu_5x5_reduce
stride 1, 1
_bottom inception_5b/relu_5x5_reduce
setup layer inception_5b/5x5
_bottom inception_5b/5x5
setup layer inception_5b/relu_5x5
_bottom inception_5a/output
kernel (3 3) pad (1 1) stride (1 1) global_pooling 0
setup layer inception_5b/pool
stride 1, 1
_bottom inception_5b/pool
setup layer inception_5b/pool_proj
_bottom inception_5b/pool_proj
setup layer inception_5b/relu_pool_proj
_bottom inception_5b/relu_1x1
_bottom inception_5b/relu_3x3
_bottom inception_5b/relu_5x5
_bottom inception_5b/relu_pool_proj
setup layer inception_5b/output
_bottom inception_5b/output
kernel (7 7) pad (0 0) stride (1 1) global_pooling 0
setup layer pool5/7x7_s1
_bottom pool5/7x7_s1
setup layer pool5/drop_7x7_s1
_bottom pool5/drop_7x7_s1
----BlobInfo----
Shape in nchw (1000 1024 1 1)
----------------
setup layer loss3/classifier
_bottom loss3/classifier
setup layer prob
Output shape 256 28 28
Output shape 480 28 28
Output shape 512 14 14
Output shape 512 14 14
Output shape 512 14 14
Output shape 528 14 14
Output shape 832 14 14
Output shape 832 7 7
Output shape 1024 7 7
input 1024 1 1
----BlobInfo----
Shape in nchw (1 1000 1 1)
----------------
old bottom conv2/relu_3x3 to new bottom conv2/3x3
*old bottom conv2/relu_3x3 to new bottom conv2/3x3
+old bottom conv2/relu_3x3 to new bottom conv2/3x3
Erasing layer 8 conv2/relu_3x3
Layer 8 after erasing: conv2/norm2 type LRN
old bottom inception_3a/relu_3x3 to new bottom inception_3a/3x3
*old bottom inception_3a/relu_3x3 to new bottom inception_3a/3x3
+old bottom inception_3a/relu_3x3 to new bottom inception_3a/3x3
Erasing layer 15 inception_3a/relu_3x3
Layer 15 after erasing: inception_3a/5x5_reduce type Convolution
old bottom inception_3b/relu_3x3 to new bottom inception_3b/3x3
*old bottom inception_3b/relu_3x3 to new bottom inception_3b/3x3
+old bottom inception_3b/relu_3x3 to new bottom inception_3b/3x3
Erasing layer 28 inception_3b/relu_3x3
Layer 28 after erasing: inception_3b/5x5_reduce type Convolution
old bottom inception_4a/relu_3x3 to new bottom inception_4a/3x3
*old bottom inception_4a/relu_3x3 to new bottom inception_4a/3x3
+old bottom inception_4a/relu_3x3 to new bottom inception_4a/3x3
Erasing layer 42 inception_4a/relu_3x3
Layer 42 after erasing: inception_4a/5x5_reduce type Convolution
old bottom inception_4b/relu_3x3 to new bottom inception_4b/3x3
*old bottom inception_4b/relu_3x3 to new bottom inception_4b/3x3
+old bottom inception_4b/relu_3x3 to new bottom inception_4b/3x3
Erasing layer 55 inception_4b/relu_3x3
Layer 55 after erasing: inception_4b/5x5_reduce type Convolution
old bottom inception_4c/relu_3x3 to new bottom inception_4c/3x3
*old bottom inception_4c/relu_3x3 to new bottom inception_4c/3x3
+old bottom inception_4c/relu_3x3 to new bottom inception_4c/3x3
Erasing layer 68 inception_4c/relu_3x3
Layer 68 after erasing: inception_4c/5x5_reduce type Convolution
old bottom inception_4d/relu_3x3 to new bottom inception_4d/3x3
*old bottom inception_4d/relu_3x3 to new bottom inception_4d/3x3
+old bottom inception_4d/relu_3x3 to new bottom inception_4d/3x3
Erasing layer 81 inception_4d/relu_3x3
Layer 81 after erasing: inception_4d/5x5_reduce type Convolution
old bottom inception_4e/relu_3x3 to new bottom inception_4e/3x3
*old bottom inception_4e/relu_3x3 to new bottom inception_4e/3x3
+old bottom inception_4e/relu_3x3 to new bottom inception_4e/3x3
Erasing layer 94 inception_4e/relu_3x3
Layer 94 after erasing: inception_4e/5x5_reduce type Convolution
old bottom inception_5a/relu_3x3 to new bottom inception_5a/3x3
*old bottom inception_5a/relu_3x3 to new bottom inception_5a/3x3
+old bottom inception_5a/relu_3x3 to new bottom inception_5a/3x3
Erasing layer 108 inception_5a/relu_3x3
Layer 108 after erasing: inception_5a/5x5_reduce type Convolution
old bottom inception_5b/relu_3x3 to new bottom inception_5b/3x3
*old bottom inception_5b/relu_3x3 to new bottom inception_5b/3x3
+old bottom inception_5b/relu_3x3 to new bottom inception_5b/3x3
Erasing layer 121 inception_5b/relu_3x3
Layer 121 after erasing: inception_5b/5x5_reduce type Convolution
input size 150528 parts size 150528
Forward
layer conv1/7x7_s2 type Convolution spent 158.054167ms
layer conv1/relu_7x7 type ReLU spent 5.689833ms
layer pool1/3x3_s2 type Pooling spent 19.716958ms
layer pool1/norm1 type LRN spent 69.234666ms
layer conv2/3x3_reduce type Convolution spent 15.302583ms
layer conv2/relu_3x3_reduce type ReLU spent 1.325625ms
Too many args to microtask: 21!

2、my.feathermodel
++++++Start Loader++++++
Finished loading from file
-- Loading 39 layers
input num 1 input dim num 4
input_name data (n c h w) (1 3 32 32)
stride 1, 1
_bottom data
setup layer conv0
_bottom conv0
setup layer relu0
stride 1, 1
_bottom relu0
setup layer conv1/1
_bottom conv1/1
setup layer conv1/1_relu
stride 1, 1
_bottom conv1/1_relu
setup layer conv1/e1
_bottom conv1/e1
setup layer conv1/e1_relu
_bottom conv1/e1_relu
kernel (3 3) pad (0 0) stride (2 2) global_pooling 0
setup layer conv1/e1_pool
stride 2, 2
_bottom conv1/1_relu
setup layer conv1/s3
_bottom conv1/s3
setup layer conv1/s3_relu
_bottom conv1/e1_pool
_bottom conv1/s3_relu
setup layer conv1/concat
_bottom conv1/concat
setup layer conv1/concat_BN
stride 1, 1
_bottom conv1/concat_BN
setup layer conv2/1
_bottom conv2/1
setup layer conv2/1_relu
stride 1, 1
_bottom conv2/1_relu
setup layer conv2/e1
_bottom conv2/e1
setup layer conv2/e1_relu
_bottom conv2/e1_relu
kernel (3 3) pad (0 0) stride (2 2) global_pooling 0
setup layer conv2/e1_pool
stride 2, 2
_bottom conv2/1_relu
setup layer conv2/s3
_bottom conv2/s3
setup layer conv2/s3_relu
_bottom conv2/e1_pool
_bottom conv2/s3_relu
setup layer conv2/concat
_bottom conv2/concat
setup layer conv2/concat_BN
stride 1, 1
_bottom conv2/concat_BN
setup layer conv3/1
_bottom conv3/1
setup layer conv3/1_relu
stride 1, 1
_bottom conv3/1_relu
setup layer conv3/e1
_bottom conv3/e1
setup layer conv3/e1_relu
_bottom conv3/e1_relu
kernel (3 3) pad (0 0) stride (2 2) global_pooling 0
setup layer conv3/e1_pool
stride 2, 2
_bottom conv3/1_relu
setup layer conv3/s3
_bottom conv3/s3
setup layer conv3/s3_relu
_bottom conv3/e1_pool
_bottom conv3/s3_relu
setup layer conv3/concat
_bottom conv3/concat
setup layer conv3/concat_BN
stride 1, 1
_bottom conv3/concat_BN
setup layer conv_cls
Layer type PReLU not registered
setup layer relu_cls
_bottom relu_cls
setup layer conv_cls_BN
stride 1, 1
_bottom conv_cls_BN
setup layer fc_cls
_bottom fc_cls
setup layer cls_prob
stride 1, 1
_bottom conv3/concat_BN
setup layer conv_reg
Layer type PReLU not registered
setup layer relu_reg
_bottom relu_reg
setup layer conv_BN_reg
stride 1, 1
_bottom conv_BN_reg
setup layer fc_reg
Output shape 32 16 16
Output shape 64 8 8
Output shape 64 4 4
Segmentation fault

**Comment by sxsxsx** [comment]
I'm glad to receive your reply，I solved this problem by using upgrade_net_proto_binary.exe to upgrade the bvlc_googlenet.caffemodel ，and it is successful to conver the caffemodel to the feathermodel，but I have new questions while running on the rk3288(armeabi-v7a)
host:ubantu16.04 NDK r17

Forward
layer conv1/7x7_s2 type Convolution spent 158.054167ms
layer conv1/relu_7x7 type ReLU spent 5.689833ms
layer pool1/3x3_s2 type Pooling spent 19.716958ms
layer pool1/norm1 type LRN spent 69.234666ms
layer conv2/3x3_reduce type Convolution spent 15.302583ms
layer conv2/relu_3x3_reduce type ReLU spent 1.325625ms
Too many args to microtask: 21!

2、my.feathermodel

/test32 my.feathermodel input_3x32x32.txt 20 1
WARNING: linker: ./test32: unused DT entry: type 0x1d arg 0x6ef
WARNING: linker: ./test32: unused DT entry: type 0x6ffffffe arg 0x19a8
WARNING: linker: ./test32: unused DT entry: type 0x6fffffff arg 0x2
++++++Start Loader++++++
Finished loading from file
-- Loading 39 layers
input num 1 input dim num 4
input_name data (n c h w) (1 3 32 32)
stride 1, 1
_bottom data
setup layer conv0
_bottom conv0
setup layer relu0
stride 1, 1
_bottom relu0
setup layer conv1/1
_bottom conv1/1
setup layer conv1/1_relu
stride 1, 1
_bottom conv1/1_relu
setup layer conv1/e1
_bottom conv1/e1
setup layer conv1/e1_relu
_bottom conv1/e1_relu
kernel (3 3) pad (0 0) stride (2 2) global_pooling 0
setup layer conv1/e1_pool
stride 2, 2
_bottom conv1/1_relu
setup layer conv1/s3
_bottom conv1/s3
setup layer conv1/s3_relu
_bottom conv1/e1_pool
_bottom conv1/s3_relu
setup layer conv1/concat
_bottom conv1/concat
setup layer conv1/concat_BN
stride 1, 1
_bottom conv1/concat_BN
setup layer conv2/1
_bottom conv2/1
setup layer conv2/1_relu
stride 1, 1
_bottom conv2/1_relu
setup layer conv2/e1
_bottom conv2/e1
setup layer conv2/e1_relu
_bottom conv2/e1_relu
kernel (3 3) pad (0 0) stride (2 2) global_pooling 0
setup layer conv2/e1_pool
stride 2, 2
_bottom conv2/1_relu
setup layer conv2/s3
_bottom conv2/s3
setup layer conv2/s3_relu
_bottom conv2/e1_pool
_bottom conv2/s3_relu
setup layer conv2/concat
_bottom conv2/concat
setup layer conv2/concat_BN
stride 1, 1
_bottom conv2/concat_BN
setup layer conv3/1
_bottom conv3/1
setup layer conv3/1_relu
stride 1, 1
_bottom conv3/1_relu
setup layer conv3/e1
_bottom conv3/e1
setup layer conv3/e1_relu
_bottom conv3/e1_relu
kernel (3 3) pad (0 0) stride (2 2) global_pooling 0
setup layer conv3/e1_pool
stride 2, 2
_bottom conv3/1_relu
setup layer conv3/s3
_bottom conv3/s3
setup layer conv3/s3_relu
_bottom conv3/e1_pool
_bottom conv3/s3_relu
setup layer conv3/concat
_bottom conv3/concat
setup layer conv3/concat_BN
stride 1, 1
_bottom conv3/concat_BN
setup layer conv_cls
Layer type PReLU not registered
setup layer relu_cls
_bottom relu_cls
setup layer conv_cls_BN
stride 1, 1
_bottom conv_cls_BN
setup layer fc_cls
_bottom fc_cls
setup layer cls_prob
stride 1, 1
_bottom conv3/concat_BN
setup layer conv_reg
Layer type PReLU not registered
setup layer relu_reg
_bottom relu_reg
setup layer conv_BN_reg
stride 1, 1
_bottom conv_BN_reg
setup layer fc_reg
Output shape 32 16 16
Output shape 64 8 8
Output shape 64 4 4
Segmentation fault

**Comment by sxsxsx** [comment]
I'm glad to receive your reply，I solved this problem by using upgrade_net_proto_binary.exe to upgrade the bvlc_googlenet.caffemodel ，and it is successful to conver the caffemodel to the feathermodel，but I have new questions while running on the rk3288(armeabi-v7a)
host:ubantu16.04 NDK r17

1、bvlc_googlenet.feathermodel
Forward
layer conv1/7x7_s2 type Convolution spent 158.054167ms
layer conv1/relu_7x7 type ReLU spent 5.689833ms
layer pool1/3x3_s2 type Pooling spent 19.716958ms
layer pool1/norm1 type LRN spent 69.234666ms
layer conv2/3x3_reduce type Convolution spent 15.302583ms
layer conv2/relu_3x3_reduce type ReLU spent 1.325625ms
Too many args to microtask: 21!

2、my.feathermodel

/test32 my.feathermodel input_3x32x32.txt 20 1
WARNING: linker: ./test32: unused DT entry: type 0x1d arg 0x6ef
WARNING: linker: ./test32: unused DT entry: type 0x6ffffffe arg 0x19a8
WARNING: linker: ./test32: unused DT entry: type 0x6fffffff arg 0x2
++++++Start Loader++++++
Finished loading from file
-- Loading 39 layers
input num 1 input dim num 4
input_name data (n c h w) (1 3 32 32)
stride 1, 1
_bottom data
setup layer conv0
_bottom conv0
setup layer relu0
stride 1, 1
_bottom relu0
setup layer conv1/1
_bottom conv1/1
setup layer conv1/1_relu
stride 1, 1
_bottom conv1/1_relu
setup layer conv1/e1
_bottom conv1/e1
setup layer conv1/e1_relu
_bottom conv1/e1_relu
kernel (3 3) pad (0 0) stride (2 2) global_pooling 0
setup layer conv1/e1_pool
stride 2, 2
_bottom conv1/1_relu
setup layer conv1/s3
_bottom conv1/s3
setup layer conv1/s3_relu
_bottom conv1/e1_pool
_bottom conv1/s3_relu
setup layer conv1/concat
_bottom conv1/concat
setup layer conv1/concat_BN
stride 1, 1
_bottom conv1/concat_BN
setup layer conv2/1
_bottom conv2/1
setup layer conv2/1_relu
stride 1, 1
_bottom conv2/1_relu
setup layer conv2/e1
_bottom conv2/e1
setup layer conv2/e1_relu
_bottom conv2/e1_relu
kernel (3 3) pad (0 0) stride (2 2) global_pooling 0
setup layer conv2/e1_pool
stride 2, 2
_bottom conv2/1_relu
setup layer conv2/s3
_bottom conv2/s3
setup layer conv2/s3_relu
_bottom conv2/e1_pool
_bottom conv2/s3_relu
setup layer conv2/concat
_bottom conv2/concat
setup layer conv2/concat_BN
stride 1, 1
_bottom conv2/concat_BN
setup layer conv3/1
_bottom conv3/1
setup layer conv3/1_relu
stride 1, 1
_bottom conv3/1_relu
setup layer conv3/e1
_bottom conv3/e1
setup layer conv3/e1_relu
_bottom conv3/e1_relu
kernel (3 3) pad (0 0) stride (2 2) global_pooling 0
setup layer conv3/e1_pool
stride 2, 2
_bottom conv3/1_relu
setup layer conv3/s3
_bottom conv3/s3
setup layer conv3/s3_relu
_bottom conv3/e1_pool
_bottom conv3/s3_relu
setup layer conv3/concat
_bottom conv3/concat
setup layer conv3/concat_BN
stride 1, 1
_bottom conv3/concat_BN
setup layer conv_cls
Layer type PReLU not registered
setup layer relu_cls
_bottom relu_cls
setup layer conv_cls_BN
stride 1, 1
_bottom conv_cls_BN
setup layer fc_cls
_bottom fc_cls
setup layer cls_prob
stride 1, 1
_bottom conv3/concat_BN
setup layer conv_reg
Layer type PReLU not registered
setup layer relu_reg
_bottom relu_reg
setup layer conv_BN_reg
stride 1, 1
_bottom conv_BN_reg
setup layer fc_reg
Output shape 32 16 16
Output shape 64 8 8
Output shape 64 4 4
Segmentation fault
