### ISSUE TITLE
sgemm.cpp:block_sgemm_external_pack_threading_8x8, block_sgemm_external_pack_threading

### ISSUE THREAD

**Issue by ejianzheng** [Tencent/FeatherCNN#19]
unsigned int tN = N / num_threads / factor;
    tN = (tN + 7) & 0xFFFFFFF8;

for example:
if N = 26 && num_threads = 3
tN = 8;
 thread task:8 8 8
but left 26-24= 2

**Comment by turbo0628** [comment]
All SGEMM related functions are under reconstruction, please wait for a few days and these things will be fixed.

**Comment by turbo0628** [comment]
Close
