### ISSUE TITLE
build出错

### ISSUE THREAD

**Issue by sanfooh** [Tencent/FeatherCNN#20]
运行
`./build_scripts/build_linux.sh	`

报错
`In file included from /output/FeatherCNN/src/layer_factory.cpp:39:0:
/output/FeatherCNN/src/layers/filter_layer.h: In constructor ‘feather::FilterLayer::FilterLayer(const feather::LayerParameter*, const RuntimeParameter<float>*)’:
/output/FeatherCNN/src/layers/filter_layer.h:29:39: error: ‘const struct feather::LayerParameter’ has no member named ‘filter_param’
             num_output = layer_param->filter_param()->num_output();
                                       ^
src/CMakeFiles/feather.dir/build.make:101: recipe for target 'src/CMakeFiles/feather.dir/layer_factory.cpp.o' failed
make[2]: *** [src/CMakeFiles/feather.dir/layer_factory.cpp.o] Error 1
CMakeFiles/Makefile2:87: recipe for target 'src/CMakeFiles/feather.dir/all' failed`

ubuntu 16.04

**Comment by sanfooh** [comment]
删除项目，重新下载生成，生成正常。

**Comment by Mengjintao** [comment]
我这边验证是可以正常编译的， 谢谢使用.

sanfooh <notifications@github.com> 于2018年6月24日周日 下午6:04写道：
