### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by yljyuan** [Tencent/FeatherCNN#23]
./build_scripts/build_android.sh 在macos(ndkr17b)编译不通过有如下错误
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target `install'.  Stop.
请问是什么问题，需要如何解决？

**Comment by Mengjintao** [comment]
您好，yljyuan
      我们没有在macos下面测试过，你可否按照wiki文档（
https://github.com/Tencent/FeatherCNN/wiki/Android-ADB-Guide）在ubuntu下面交叉编译？
      我再检查测试一下macos看怎么编译，然后更新macos交叉编译文档。
      谢谢。

Best,
Jintao

yljyuan <notifications@github.com> 于2018年7月24日周二 下午6:57写道：
