### ISSUE TITLE
Model Convert Errror

### ISSUE THREAD

**Issue by kdhs114** [Tencent/FeatherCNN#25]
Hi, thank you for your hard works on Feather CNN. I need help to run Benchmark on different networks. 

Seen this Benchmark result of different networks, mobilenet, squeezenet, googlenet and VGG16. 
https://github.com/Tencent/FeatherCNN/wiki/Benchmarks
Can you share feathermodel file you used, please? 

I've tried to convert some caffe models (prototxt / caffe model upgraded)  into feathermodel using tools/feather_convert_caffe, and hits an error.
**_[libprotobuf FATAL /HDD/usr/local/include/google/protobuf/repeated_field.h:1431] CHECK failed: (index) < (current_size_): 
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: (index) < (current_size_): 
Aborted_**
Note : MobileNet, and SqueezeNet hits the same error. 

I've found an way to work around, 
in feather_convert_caffe.cc:217
_layer_num = net_param.layer_size();_ change this to _layer_num = net_param_prototxt.layer_size();_

-> which makes the conversion works, and MobileNet benchmark runs without issues. 

However, Squeezenet hits another issue on Benchmark Run. 
_++++++Start Loader++++++
Finished loading from file
feather_benchmark: /root/feather/src/flatbuffers/flatbuffers.h:242: flatbuffers::Vector<T>::return_type flatbuffers::Vector<T>::Get(flatbuffers::uoffset_t) const [with T = flatbuffers::Offset<feather::BlobProto>; flatbuffers::Vector<T>::return_type = const feather::BlobProto*; flatbuffers::uoffset_t = unsigned int]: Assertion `i < size()' failed.
Aborted_

I guess this comes from layer_num mismatches where I've changed the layer_num to prototxt's. But if I didn't, conversion to feathermodel would fail in first place.

Can you shed some lights on this, please?

Another, 
How do I create input data file, please? repo has input_3x224x224, but shouldn't alexnet use input_3x227x227? Not sure where the input file comes from, so cannot create one for 227x227. Missing some points maybe?

Thanks!

**Comment by Mengjintao** [comment]
Hi kdhs114, 
     Thanks for your analysis on FeatherCNN and bug report on our convert tools. 
     Currently, we are upgrading the model convert tools.  It will be finished hopefully in one week. 
     We are also plan to provide a model zone for FeatherCNN to easy your benchmark (http://hpcc.siat.ac.cn/jintao/feathercnn/). I will check everything is right first and give you my notice asap. 

Best, 
Jintao Meng
