### ISSUE TITLE
cannot execute binary file.这个是我在PC上的linux出错了，请问是什么问题呢

### ISSUE THREAD

**Issue by SummerLife** [Tencent/FeatherCNN#26]
bash: ./feather_benchmark: cannot execute binary file: Exec format error

**Comment by Mengjintao** [comment]
Hi SummerLife, 
    We provide cross compiler support for X86 platform, but the execute binary file can not run on X86 platform. You need to copy this file to an ARM platform and test it as you wish. 

Best,
Jintao Meng

**Comment by SummerLife** [comment]
I got it. Many thanks!
