### ISSUE TITLE
Do you plan to support convert pytorch model to feathercnn model?

### ISSUE THREAD

**Issue by hcsearch** [Tencent/FeatherCNN#29]

**Comment by Mengjintao** [comment]
Hi hcsearch, 
    No, and it is not necessary to specially support pytorch model in feathercnn. 
    As far as I know, Caffe2 has been combined into Pytorch. A tutorial in their official site has been provided to transform the model from pytorch to Caffe2 with ONNX.  Then Caffe2 model can be transform to caffe model, which is naturally supported by feathercnn.  Please refer to this site 
 https://pytorch.org/tutorials/advanced/super_resolution_with_caffe2.html, for more information.  

Jintao Meng

**Comment by NikolaMr** [comment]
Hi @Mengjintao !

I have the same use case as the @hcsearch but I haven't been able to convert the Caffe2 model to Caffe model. Is there some kind of tool for that purpose that you know of? Could you please link it to me? I've been searching for it but I haven't been successful in my search...

Best regards,
Nikola Mrzljak
