### ISSUE TITLE
Net::ExtractBlob() error

### ISSUE THREAD

**Issue by Orangels** [Tencent/FeatherCNN#4]
我在跑 ios 程序的时候 ,最后输出结果时调用 Net::ExtractBlob(float** output_ptr, std::string name) 这个函数报错 
调用部分代码是这样的:
float **p = NULL;
forward_net.ExtractBlob(&p, "fc7");
请问是这个 指针初始化的问题么?
在这个  forward_net.ExtractBlob(float** output_ptr, std::string name) 实现里给数组指针分配内存,在函数内部为什么要
assert(output_ptr == NULL);

**Comment by Mengjintao** [comment]
You need to allocate memory in advance for that output data pointer to receive the return data.

**Comment by turbo0628** [comment]
Hi orangles, 我更新了API，原先的实现十分不友好，请再试一下
