### ISSUE TITLE
ConvolutionDepthwise 在模型转换阶段未做适配

### ISSUE THREAD

**Issue by tianylijun** [Tencent/FeatherCNN#8]
ConvolutionDepthwise 在模型转换阶段未做适配，需要修改group为num_output

**Comment by Mengjintao** [comment]
Group is defined to support group convolutional layer.  As this parameter is rarely used, except the ancient neural network AlexNet, currently we actually DO NOT support it, thus can NOT implement AlexNet. 

We will close this issue until it has been supported.  Thanks for your attention on this work.

**Comment by turbo0628** [comment]
Adapted
