### ISSUE TITLE
Mobilenet Forward twice, result is wrong

### ISSUE THREAD

**Issue by tianylijun** [Tencent/FeatherCNN#9]
As title

**Comment by tianylijun** [comment]
bug in BN arm layer，with BN generic api, result is ok

**Comment by Mengjintao** [comment]
Thanks for your kindly report.    
Can you send the related input data and model to me  (meng.jintao@gmail.com)  for bug reproducing?

**Comment by turbo0628** [comment]
The previous SGEMM version has memory issue. We've fixed that with the lastest SGEMM. Thanks for reports!
